### PR TITLE
put robot mounting/unmount moves in robot_online blocks

### PR DESCRIPTION
**Pull request by JunAishima**
* make sure calls to actual robot moves are blocked away within
   if getBlConfig('robot_online'): blocks
 * refs #175

### CODE REVIEW

**Comment by JunAishima** [comment]
need to test before making a full pull request.

**Comment by RobertSchaffer1** [comment]
Should probably put in an else block with some logging of why it's doing nothing.

**Comment by JunAishima** [comment]
> related to this, the robot_lib code to handle status is broken - it should not be using return value from RE() to get its status as this is not necessarily the value that is returned from the function call. The return value from RE() is the status of the plan.
> 
> two possible approaches:
> 
>     * use the documented RunEngineResult object to extract the function return value
> 
>     * use the success or failure flags from the RE() call for making decisions. care would be needed to ensure that failures are correctly handled

OK - our LSDC is still using an old Bluesky, so we can't use RunEngineResult. have implemented a check after the plan to see whether a pin is mounted as expected. this will determine whether the step fails or succeeds.

need to think about how this will work with EMBL robot server in the future

**Comment by JunAishima** [comment]
@RobertSchaffer1 - commit https://github.com/NSLS-II/lsdc/pull/176/commits/125c4058d8390d5651cd0e14c4bf07d99b2b9700 is an improvement made upon your suggestion

**Review by RobertSchaffer1 — APPROVED** [review]
Looks fine to me, in principle we could merge the mount and unmount since they only differ very slightly, but in practice this is probably just as good.

**Pull request merged**
