### PR TITLE
Disabling more buttons for NYX user operations

### PR DESCRIPTION
**Pull request by mskinner5278**
disabled	staff		Home Pins	self.homePinsButton
disabled	staff		Set Fast DP Node and the 4 related boxes	self.setFastDPNodesButton
disabled	staff		Set Spotfinder Nodes and associated 8 boxes	self.setSpotNodesButton
disabled	staff		Not sure what Unlock and Lock are for	self.lockGuiButton
disabled	staff		Not sure what Unlock and Lock are for	self.unLockGuiButton
				
				
disabled	staff	Robot	Recover Robot	self.recoverRobotButton
disabled	staff	Robot	Reboot EMBL	self.rebootEMBLButton
disabled	staff	Robot	Start EMBL	self.restartEMBLButton
disabled	staff	Robot	Open Gripper	self.openGripperButton
disabled	staff	Robot	Close Gripper	self.closeGripperButton
disabled	staff	Robot	Open Port 1	self.openPort1Button
disabled	staff	Robot	Close Ports	self.closePortsButton
disabled	staff	Robot	Unmount Cold	self.unmountColdButton
disabled	staff	Robot	Dry Gripper	self.warmupButton
disabled	staff	Robot	Enable Dewar TScreen	self.enableTScreenButton
disabled	staff	Robot	Park Gripper	self.parkButton
				
already disabled	collection params		Protocol selector	protoStandardRadio, protoRasterRadio, protoVectorRadio, protoOtherRadio
disabled			Vector Start	setVectorStartButton
disabled			Vector End	setVectorEndButton
disabled			Number of Wedges	self.vectorFPP_ledit
need more info			Far lower left buttons

### CODE REVIEW

**Comment by JunAishima** [comment]
I have removed the "Warmup Gripper" button.

the Set FastDP Nodes boxes to enter values still seem to be working, as well as the Set Spotfinder Nodes ones. there are no series of multiple boxes in the pull request.

**Comment by JunAishima** [comment]
@mskinner5278 can you please find the multiple buttons for the "Set FastDP Nodes" and "Set Spotfinder Nodes" and disable those? thanks

**Comment by JunAishima** [comment]
@mskinner5278 could you pull this code onto your system or the beamline when there is time and verify that the code works as expected? ideally put a snapshot in here

**Comment by mskinner5278** [comment]
I rebased this onto the latest nyx_ophyd, confirmed all of the buttons from #210 were disabled.  
But I have re-enabled the protocol box to include only the standard and vector scans on NYX and the associated vector start and vector end buttons.

**Pull request closed without merging**
