### PR TITLE
Vector program

### PR DESCRIPTION
**Pull request by mrakitin**
This was supposed to be done via #28, and I was too fast to merge it to master (currently reverted via #30).

### CODE REVIEW

**Comment by mrakitin** [comment]
Bump @JunAishima @MikeHart85

**Review by JunAishima — APPROVED** [review]
yes, I am happy with these

**Review by MikeHart85 — APPROVED** [review]
Looks good. My bad, forgot we were meant to target this branch rather than master when we were doing this.

**Comment by mrakitin** [comment]
Reverting of #28 brought a few commits to `master`:
image

@JunAishima, do you want to remove the commits after October 22? I can clean the history out of them.

**Comment by mrakitin** [comment]
Thanks for your quick replies, @JunAishima and @MikeHart85. Feel free to merge.

Need to decide what we do with `master` (see above).

**Pull request merged**
